### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by thefinn93** [rosjat/python-scsi#59]
I've been playing with this library for a bit and it seems like it shouldn't be too hard to add Python 3 support, any plans to do so?

**Comment by rosjat** [comment]
hi,

the c module is ready for python 3 (Im not the c magican but the code I add lately was for python3) and the python code should work with python 3 as well ( at least what I tested so far). I need to check some stuff since the __metaclass__ seems to be broken in python3. But I use the lib for the mtx-gui project of mine and this is runs in python3 (al least the dev branch does). So just give it a try with python3 and give me feedback :)

**Comment by thefinn93** [comment]
Yeah I ran into issues with the metaclass stuff, so I Googled briefly (and got [here](https://python-3-patterns-idioms-test.readthedocs.org/en/latest/Metaprogramming.html)) and it looks like this worked:


```diff
diff --git a/pyscsi/pyscsi/scsi_command.py b/pyscsi/pyscsi/scsi_command.py
index 272ddcc..99bc742 100644
--- a/pyscsi/pyscsi/scsi_command.py
+++ b/pyscsi/pyscsi/scsi_command.py
@@ -19,11 +19,10 @@
 from pyscsi.pyscsi.scsi_exception import SCSIDeviceCommandExceptionMeta as ExMETA
 
 
-class SCSICommand(object):
+class SCSICommand(object, metaclass=ExMETA):
     """
     The base class for a derived scsi command class
     """
-    __metaclass__ = ExMETA
 
     def __init__(self, scsi, dataout_alloclen, datain_alloclen):
         """
diff --git a/pyscsi/pyscsi/scsi_device.py b/pyscsi/pyscsi/scsi_device.py
index 22d99ce..9220dcd 100644
--- a/pyscsi/pyscsi/scsi_device.py
+++ b/pyscsi/pyscsi/scsi_device.py
@@ -33,11 +33,10 @@ except ImportError as e:
     _have_linux_sgio = False
 
 
-class SCSIDevice(object):
+class SCSIDevice(object, metaclass=ExMETA):
     """
     The base class for a derived  scsi device class
     """
-    __metaclass__ = ExMETA
 
     def __init__(self, device, readwrite=False):
         """
```

I'm currently running into an issue that appears to not be specific to python 3, and possibly something wrong with my device, so I haven't been able to get much further

**Comment by rosjat** [comment]
like I said I ran into this metaclass issue myself as I was testing my mtx-gui project. Oh so now you need wierd inheritance for this. I'll give it a shot later when Im home .

**Comment by rosjat** [comment]
I need to check if this is backward compatible with 2.x, if not we might need to make a new branch for python 3

**Comment by rosjat** [comment]
okay I checked and this seems to be a python 3.x feature only, so you could easily change it in your local code for now. I'll see if we may make a seperate branch for 3.x or maybe a subpackage with 3.x code and check for it at setup time to use it

**Comment by rosjat** [comment]
I will add code that makes the metaclass useage compatible for python 2 and 3 this weekend. It's basically something like that 

 from future.utils import with_metaclass class

class BaseForm(object): 
    pass 

class FormType(type): 
    pass


Form(with_metaclass(FormType, BaseForm)): 
    pass

This is just to illustrate the use of future ... Of course
