### ISSUE TITLE
error return without exception set

### ISSUE THREAD

**Issue by thefinn93** [rosjat/python-scsi#60]
So, as mentioned in the other issue, I'm running into something that I don't know how to fix/deal with:

```
$ python mtx.py -f /dev/sg4 status
Traceback (most recent call last):
  File "mtx.py", line 152, in <module>
    main()
  File "mtx.py", line 121, in main
    alloclen=16384).result['element_status_pages'][0]['element_descriptors']
  File "/home/finn/diskchanger/local/lib/python2.7/site-packages/pyscsi/pyscsi/scsi.py", line 308, in readelementstatus
    return ReadElementStatus(self, start, num, **kwargs)
  File "/home/finn/diskchanger/local/lib/python2.7/site-packages/pyscsi/pyscsi/scsi_cdb_readelementstatus.py", line 80, in __init__
    self.execute()
  File "/home/finn/diskchanger/local/lib/python2.7/site-packages/pyscsi/pyscsi/scsi_command.py", line 76, in execute
    self.scsi.device.execute(self.cdb, self.dataout, self.datain, self.sense)
  File "/home/finn/diskchanger/local/lib/python2.7/site-packages/pyscsi/pyscsi/scsi_device.py", line 97, in execute
    status = linux_sgio.execute(self._fd, cdb, dataout, datain, sense)
SystemError: error return without exception set
```

this is running the `mtx.py` straight out of `python-scsi/tools`. "real" mtx handles this device fine, so I'm starting to suspect it's not the device. How should I proceed? I don't know much about debugging C stuff (especially in python)

**Comment by thefinn93** [comment]
Should mention that this is with python 2, although the same thing happens with 3

**Comment by rosjat** [comment]
hmm I'll take a look, what kind of device you use there?

**Comment by thefinn93** [comment]
A Sony XL1B2 media changer.

**Comment by rosjat** [comment]
okay thx, 

like I said I'll take a look at the code tonight, still at work ;)

**Comment by thefinn93** [comment]
Alrighty, I'm about to go to bed anyway (wee timezones!). Thanks for the response and please let me know if there's anything you need me to check or test or whatever

**Comment by rosjat** [comment]
I'll do It's nice to get some real feedback :)

**Comment by thefinn93** [comment]
Wellp, turns out I didn't go to sleep. Looks like this *is* an issue with my changer that mtx has a special workaround for. I forgot that I always have to use `altres` when using mtx, went and looked it up in the mtx source (because it's not mentioned anywhere on the man pages, and:


```c
static void AltReadElementStatus(void)
{
	/* use alternative way to read element status from device - used to support XL1B2 */
	SCSI_Flags.querytype = MTX_ELEMENTSTATUS_READALL;
}
```

It's some special hax for my changer. I'll post if I get anything more useful

**Comment by rosjat** [comment]
yeah the evil hacks :) but I will get a look at the metaclass code anyway

**Comment by rosjat** [comment]
I will add code that makes the metaclass useage compatible for python 2 and 3 this weekend. It's basically something like that 

 from future.utils import with_metaclass class

class BaseForm(object): 
    pass 

class FormType(type): 
    pass


Form(with_metaclass(FormType, BaseForm)): 
    pass

This is just to illustrate the use of future ... Of course
