### ISSUE TITLE
No package on pypi?

### ISSUE THREAD

**Issue by Flameeyes** [rosjat/python-scsi#66]
Hello, I'm trying to build a package for my glucometerutils project, which uses python-scsi for one of the drivers. Unfortunately it does not seem like there's a python-scsi package on pypi I can depend on (which also makes testing hard).

Any hope to have a release? It does not look like there have been any chances in nearly two years, so just a snapshot would do fine IMHO.

Thanks!

**Comment by rosjat** [comment]
Hi all,

I'm meeting with Ronnie in a few days and like to talk about a few things
regarding the project. I was quiet occupied the last months with other
things but I will start working on python- SCSI again in 2018. I will take
a look at the requirements for pypy and try to make the released version
available there.

It will not happen the next few days but if its possible I try to do it in
January.

Regards

Markus

Am 01.01.2018 3:08 nachm. schrieb "Diego Elio Pettenò" <
notifications@github.com>:

**Comment by rosjat** [comment]
Hey there,

i did setup a pypi package for pyscsi now so if you want to give it a try..
its version 1.0 so not the current master, its also just a source dist so no wheel was build
