### ISSUE TITLE
Why using Python extensions instead of fcntl

### ISSUE THREAD

**Issue by hrchu** [rosjat/python-scsi#68]
Just curious, why you  use Python extensions to implement sgio instead of ```fcntl```? Is there any performance issue or?

**Comment by rosjat** [comment]
To be honest I dont know if it there is a performance penalty with the fcntl module. 

We went for this approach because we used the scsi generic driver and I dont see any support for that in the fcntl module. You might noticed the  sg_io_hdr_t struct  in the execute method of the extention.
