### ISSUE TITLE
Missing file pyscsi/pyscsi/scsi_cdb_report_supported_opcodes.py

### ISSUE THREAD

**Issue by jkua** [rosjat/python-scsi#69]
I checked out the current master branch, 230b5b89d2e39a4fef4e25210cd66b2b7c575577 , and it appears that at least one file is missing as I get:

```
>>> import pyscsi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pyscsi/__init__.py", line 1, in <module>
    from .pyscsi import *
  File "/usr/local/lib/python3.6/dist-packages/pyscsi/pyscsi/scsi.py", line 39, in <module>
    from pyscsi.pyscsi.scsi_cdb_report_supported_opcodes import ReportSupportedOperationCodes
ModuleNotFoundError: No module named 'pyscsi.pyscsi.scsi_cdb_report_supported_opcodes'

```

**Comment by rosjat** [comment]
oh sorry this code wasn't suppose to get commited :( 

I will remove the import asap, the function is still in the making

**Comment by rosjat** [comment]
I just removed the import and the function for ReportSupportedOpcodes from scsi.py so this should fix this problem.
