### ISSUE TITLE
linux_sgio_execute does not return host/device code in hd_status when sense_buffer is empty in contingent allegiance condition

### ISSUE THREAD

**Issue by hrchu** [rosjat/python-scsi#76]
https://github.com/rosjat/python-scsi/blob/master/linux_sgio/sgiomodule.c#L257

When `io_hdr.sb_len_wr` is zero, , (`io_hdr.status`| `io_hdr.host_status` | `io_hdr.driver_status`) may provide additional information such as timeout besides the sense buffer. Current codebase just returns `SCSI_STATUS_SGIO_ERROR`  here with no more information.

Example error handling code:
```
   if ((io_hdr.info & SG_INFO_OK_MASK) != SG_INFO_OK) {
        if (io_hdr.sb_len_wr > 0) {
            printf("INQUIRY sense data: ");
            for (k = 0; k < io_hdr.sb_len_wr; ++k) {
                if ((k > 0) && (0 == (k % 10)))
                    printf("\n  ");
                printf("0x%02x ", sense_buffer[k]);
            }
            printf("\n");
        }
        if (io_hdr.masked_status)
            printf("INQUIRY SCSI status=0x%x\n", io_hdr.status);
        if (io_hdr.host_status)
            printf("INQUIRY host_status=0x%x\n", io_hdr.host_status);
        if (io_hdr.driver_status)
            printf("INQUIRY driver_status=0x%x\n", io_hdr.driver_status);
    }
```

In pyscsi pkg, `SCSICheckCondition` may add additional argument that accept host/driver status.

@rosjat I don't know how are you going to deal with this, so I just leave an issue here instead of PR.

**Comment by rosjat** [comment]
well the intent of this was never to handle errors other then a sense codes from the scsi device in the python module . If you like to get more informations simply propose something to handle it up in the python module. oviously a printf in the c module isnt going to achieve this.  starting point would be to make the SGIOError return more information in the c module and then accordingly improve the error handling in the python module.

**Comment by rosjat** [comment]
i will close this now since it is not related to the python-scsi lib directly
